[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["../lib"]
out = "../out"
cache_path = "../cache"

solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "forge-std/=../lib/forge-std/src/"
]

fs_permissions = [
    { access = "read-write", path = "../deployments" },
    { access = "read", path = "../" }
]
